stages:
  - build
  - test
  - deploy
image: docker
services:
  - docker
builder:
  stage: build
  script:
    - docker build --squash -t $CI_REGISTRY/CI_PROJECT_PATH/hello:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/CI_PROJECT_PATH/hello:gitlab-$CI_COMMIT_SHORT_SHA
  except:
    - main
deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
  only:
    - main
