apiVersion: apps/v1
kind: Depoyment
metadata:
  labels:
    app: dep2
  name: dep2-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep2
  template:
    metadata:
      labels:
        app: dep2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dep2-html-vol
          mountPath: /usr/share/nginx/html

      volumes:
      - name: dep2-html-vol
        configMap:
          name: dep2-cgfmap-html

---
apiVersion: v1
kind: Service
metadata:
  name: dep2-svc
spec:
  selector:
    app: dep2
  ports:
  - name: dep2-svc-http-port
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dep2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ubuntu-001.dgt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dep2-svc
            port:
              number: 80
  tls:
  - hosts:
    - ubuntu-001.dgt.local
    secretName: dep2-secret-tls

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dep2-cgfmap-html
data:
  index.html: |
    <html>
      <body>
        <h1>Hello, I am nginx SSL.</h1>
      </body>
    </html>


---
apiVersion: v1
kind: Secret
metadata:
  name: dep2-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuekNDQTRlZ0F3SUJBZ0lVUGUyVk1GR1pN
    OEkwMkxoNUQ0dXNFckl2QkZJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1h6RUxNQWtHQTFVRUJoTUNV
    bFV4RERBS0JnTlZCQWdNQTAxVFN6RU1NQW9HQTFVRUJ3d0RUVk5MTVEwdwpDd1lEVlFRS0RBUlhW
    MWRCTVF3d0NnWURWUVFMREFOUGNtY3hGekFWQmdOVkJBTU1EbXQxWWk1dWIySnlMbXh2ClkyRnNN
    QjRYRFRJek1URXlPREl3TlRBME5Gb1hEVEkwTVRFeU56SXdOVEEwTkZvd1h6RUxNQWtHQTFVRUJo
    TUMKVWxVeEREQUtCZ05WQkFnTUEwMVRTekVNTUFvR0ExVUVCd3dEVFZOTE1RMHdDd1lEVlFRS0RB
    UlhWMWRCTVF3dwpDZ1lEVlFRTERBTlBjbWN4RnpBVkJnTlZCQU1NRG10MVlpNXViMkp5TG14dlky
    RnNNSUlDSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF3a3NrRi9MdGV2
    ZzB1OGIrNWYybm5pVlNqUVZXc2laRjhKZVkKYVZRK09LUUxLYUlhbkROcUQ0MVVZRjZJZTFuMGhu
    ZmpqMkxxbWJKbzMvdmVmMHY0SmFzYlBjNXVpd0VKaGlxeApOcnBlVlNGa2tzVDBkc29jYjZpcUtF
    NVhwZjdhMEU0b2l3VzRhTEpnak1wazk3VzRvOW9nMkNFOE4xdHNmOWxjCjBxd2VFbHdkUnFtQjFm
    cGdrTTZ1ZEUwR3BVMTdiWWtXU283QU5DYVJFQTBWT2NybFBWTk9mT0N0QVVLUG5ZM3UKZWRXbnBV
    WFVQU3k0c1h2L0QxMXhNNWV5ZnNTNWxBekFiaThVa2UvRzFwTVkxdTBLUUZ3cUwxRXFmMis1aFk2
    bgp4WG9TM012dXZXQ3JsaG8rQno5ZHpieGNITEZBNDUvTW1xeXM2dnJWU0pZRjBYUFdKbjVSM0d0
    ck5xejlSU3ZZCnNnWlVrK011bys5dkkyaEtzWk9ZYWhjYU52eVVGM2hyL1FsaUluMjRseThONUZz
    c3ZtUXg1V1FkM0ZOa2JsZi8KekZIVHFkTGxzZGJBTnZ1NU5Pc00xWmdtRnhxR0w2UDJuOWlqaEJW
    L1l2SlNLamtsempYRlBKNGt3UzVZdlNoWgpSL29OMjFUbHZISTlWRWdueEp4UWVpR0FNYmlJN2JD
    MC8yUSt0VUxaOWJFUHRjWFpkSEVlUnM5UVJJeUZRaU9wCkVsTHVRZmlxT0tBbitWcndHSlQvRldE
    ODg2RFNTUUZVSWNTcXNKa05pMmc4TGhzTWRBclc5NkN4eDJhcmRibnkKSXZaRWlLRUVzTEs4ekYr
    RUI3UUNBRUVvSnZTbzJRWHZpdXUwV1V4SldUbTNZakRTRzBsSlVFU0JpQ3N3cTR5NwpkeStFRWFF
    Q0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZLMzlWOHUrU2w5L05SdFJJVGxoM1BEWWE2elBNQjhH
    CkExVWRJd1FZTUJhQUZLMzlWOHUrU2w5L05SdFJJVGxoM1BEWWE2elBNQThHQTFVZEV3RUIvd1FG
    TUFNQkFmOHcKRFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUhLMEpzUWdiWEZwdnhnTXkzVmlhRGdC
    eDNYTW8vcnUvRkVvaU5EbgpqL1cwSXU4b1J5alRERS9TUHRoQ01nRmpzYmV5MDYzcFBjb1JvL1R0
    Ym5OMStTaG9PMDRHU1hsLzlCYy9XdDg0CitjSFB2Q1RCRGRKSlkxWDFXTGE2NUhGYmJPMjZ2UHZa
    WERjQzlpWHRXS2RzdUdVT2pxQUdBQWxKeEJUaXo4Y0gKbDBPTit2WjNUVFE1Q2s5aUMydzVYT0xG
    WDdxK1BNMXZ0Q2FLMUd1R0pMUjJsaTFpaU41U24xVFlGckRNbHhONgpIeHMyYmdKeWxKSG9EWGg5
    ZGE0YnpQc2lFR1NBUTVpZU9TM1Btb1drTTNNTTNhWE0zR0VNQmRuZzNiV2d6ajVTCjJzZjg4VUp5
    dmVuMklvaHBXSXpjWGRsSVZIYjQvZTZzVmN4dzI3a1ZaVzJyWXJmM2tOcTdvY2ZFczgrMkZhd2wK
    WHo3TUZIRklhMk8vZG9nbEdBbGZDTUkyNEtsZmV5SWJGdHg3MU9kRGF3WUU3VkhRZ0RjMi80VTZV
    UU9zc3Qybgo4RnhCU0dwM0x4V0J5NllWcnE0dFJQWHJoaUFFcTh1MXBSZnI4TGF3SkUxcThkc2FN
    OTN4NGV5R1BYSXBSaUlLCjFQWlZqeFVJUTUrNGJONS80aTNZb0laM0FwMjh2b1pMcGhvNWxNMDBJ
    aDFWeHlsZHNZbmoyajI0TFRQWDI1Um0KNVNwc3g2R3BnNU5QYjZudm9UeS9tRWJJaXZ5cXI4TFdr
    SnNVNzREN2gxQ3FXcS95WEl3eWVmei9PZG9KNWFTcgpDWGZNVHlWSSsvN3dINm1sUE5SS2JxN2pH
    RjAzbHJOVTRwUDNUTDRacXFnbW5zUE43dmdOVG5MT2ZLZFJxazdNCk9PSzgKLS0tLS1FTkQgQ0VS
    VElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRRENTeVFYOHUxNitEUzcKeHY3bC9hZWVKVktOQlZheUprWHds
    NWhwVkQ0NHBBc3BvaHFjTTJvUGpWUmdYb2g3V2ZTR2QrT1BZdXFac21qZgorOTUvUy9nbHF4czl6
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRRENTeVFYOHUxNitEUzcKeHY3bC9hZWVKVktOQlZheUprWHds
    NWhwVkQ0NHBBc3BvaHFjTTJvUGpWUmdYb2g3V2ZTR2QrT1BZdXFac21qZgorOTUvUy9nbHF4czl6
    bTZMQVFtR0tyRTJ1bDVWSVdTU3hQUjJ5aHh2cUtvb1RsZWwvdHJRVGlpTEJiaG9zbUNNCnltVDN0
    YmlqMmlEWUlUdzNXMngvMlZ6U3JCNFNYQjFHcVlIVittQ1F6cTUwVFFhbFRYdHRpUlpLanNBMEpw
    RVEKRFJVNXl1VTlVMDU4NEswQlFvK2RqZTU1MWFlbFJkUTlMTGl4ZS84UFhYRXpsN0oreExtVURN
    QnVMeFNSNzhiVwpreGpXN1FwQVhDb3ZVU3AvYjdtRmpxZkZlaExjeSs2OVlLdVdHajRIUDEzTnZG
    d2NzVURqbjh5YXJLenErdFZJCmxnWFJjOVltZmxIY2EyczJyUDFGSzlpeUJsU1Q0eTZqNzI4amFF
    cXhrNWhxRnhvMi9KUVhlR3Y5Q1dJaWZiaVgKTHcza1d5eStaREhsWkIzY1UyUnVWLy9NVWRPcDB1
    V3gxc0EyKzdrMDZ3elZtQ1lYR29Zdm8vYWYyS09FRlg5aQo4bElxT1NYT05jVThuaVRCTGxpOUtG
    bEgrZzNiVk9XOGNqMVVTQ2ZFbkZCNklZQXh1SWp0c0xUL1pENjFRdG4xCnNRKzF4ZGwwY1I1R3ox
    QkVqSVZDSTZrU1V1NUIrS280b0NmNVd2QVlsUDhWWVB6em9OSkpBVlFoeEtxd21RMkwKYUR3dUd3
    eDBDdGIzb0xISFpxdDF1ZklpOWtTSW9RU3dzcnpNWDRRSHRBSUFRU2dtOUtqWkJlK0s2N1JaVEVs
    WgpPYmRpTU5JYlNVbFFSSUdJS3pDcmpMdDNMNFFSb1FJREFRQUJBb0lDQUFINEt6Y3c3aFpRRy9a
    VWdWa2kzQzJZClRFRUQ0bGFWdnU1WHI5WG9yMlVzbFU1aUIxMDQ5djVhdzBqakw1NWZxeWNueUNX
    ZWJmWWozcmdTZ0dpUHQza2IKRXMxUTRYVmVwV3YzMUoxczVtTGl1SGRiL1IrVGhxK3AzQnV2ZTV0
    Ym8zaGRxbkx3dEFEc2VmTjJsdTgycHowcwpXQ2NWZk1KRTQzZjFmV0ZIVEZwVjQ3R3Q5L3B4K2ww
    enpMaExxL3NTeEVsclA4K3gzQ0hreTJJN1hoNEM4eSsxCmNzUHI0ZVVOUmw1bFgyZkE4aW43Tkxn
    ODB1azlwWjYyd0VMbDZ0Z3A2T3dOSjlhV0ZKVmx0ZWVQR1l2YlhxUzcKWGFEbWpqZ0YzbVRZZWdp
    dFRaZytXdklPUmt2SFR1c000M3NHU2FlSk16a1ZDMGpKcnhkc3Fhcjl5WUdDdFBuZwovWEx2a3kv
    b1BMZC9uSzNzakZnTUVQK3dZYVNZWjdqTE1kcnVRbnYrTDVSMVNlbkJRVWk0bldsaENTczV3b3ZG
    ClpLQ0lmMXA4TTJFY2ZYbkJac0laeENYUzBOeG9mQmdiM1VVU1FmWXB6Vi9YNXNsRVhvTStYWVNa
    TXJzRlYvbXcKbmZ1aWZOMHU5a3hTSmk1dzcvVEpOMWpGaytiOVdSUS9wYTVPaTN6L3dKOXVrNlVR
    cDN0NUVYcGFPNjRBdUpsdAp2cmwxMjFxUlJURk1uSTRleFZRR1NIRktBWVNCWlRKSU1ER1ExWTB3
    cGx3ZjRVcjFJaFFYWDF3TTVGTktWc1VOCjR6R2x1OFVjU0JoaytqSHVZWkd2ZENERStwclVxK2lY
    Vkt1M2I3ZldsYTZCdlBiZXJnWnhMbURBNTZNbzFXVmcKY1FOL3I4Y1hnN1d6bjZDcGlSc1BBb0lC
    QVFEZUpkT2RVWGVuMXl3VEJTdkIxeVZ1Q0s1VnZHdzBWVkJOdi9ucApQWXE0bGNhSGI4T3JGZlBh
    Tks5cC9LYkdtQWdXd3lQOUd0b1lOeFppQUhCZkc0M1I1RFRITXRsdlBYMXdNL3NsClVJVGV6ekNF
    QlpRZldwZ1ZqNU5ZZlJWSlFOZHBPWkJDMnh3SnBzK3VQcEVEajNZYlJ6WGtZM1dnSUVMNW01U3kK
    MTFDQy9ydDYraFVSMVl3L0pyUWZyRDY5RmJUWmlOdjN6bEJFWVUyelVYaDBGak1EdzUwRXJOZWhJ
    ekN0MTZKZApaY2NwZHAvY20vRVd6aVlmSnJnRkRjM25SQjk5Z1RqN3RNNDYrYTNxMVBJVjlXczdt
    eWxzQ1BTekhHeERneW04Cjc3VHB6dzhVZXFpVHN1YVBSVXBJQW5JQVlrY1loTkhwOEtEckptanBO
    RXYvUE9rUEFvSUJBUURmNXJKYm1VOVUKd2JJbmNMUEUxSE1LSFNiUnk1NlBOUUV4dGR4aWYxcmpL
    VERRVVM1U0VQK3ppSyt1TWxIcXJ0M2RYa3BHa2FQZgpSOUJTdU51WFJCemhnS240VytuWCtkbWp0
    RTZDeHB4aDQrbTFKUXRIVFFCNHBocWdOK0lBV2Q4dHlNK3E1N3Z5CmN6d2N4Rzg5R0J3WHhYUFEx
    b2VWRk0ySy9zQWVZN0J4dzdMMkowUEVKemFaTkJPZ3RycXFnTGEyS1ZITTA5WG4KMEZkNkVpOGRE
    L0JHNjNsb0VmKzdPYjRZcnV5Q2hpdHMyMWZRdmJtWEprQ2V1U2FiYW14SExwSXdYWmZBRXFjUgpR
    WWd5QU9iUlVYQ2dlK2JPWm9pdW4reUJkMkhUQTlCaElJSFZUQnZ3ZFkwWVZ5RmZFK2dia1NqRHJH
    NWNZdVlPCisycmJ2ZTlhNlhwUEFvSUJBRzQ3UnU1aFpvYWFkdnhaTElWYlJPOTh6MFVyNG1WMWtB
    dUVuM1hsVzlpTU9aOHIKRG1UdTE3b0hPcVBWQXN5NDFBcTNlancxL3RMVlF2NE9TYlJuNzgrZTli
    R0N3Zkk1Q08yTVhhcitjWEErVDB5egpsL1NXOTdCN05ocEt0eTFLUjVtblByWnVFMU9XdXFjejFM
    RjNscHVpa2xOcUp3djE5a1gxdGF1b3ZBTEVkRE5wCnROck1wSE1SdVgrZDhPUFN5WkxJSHA2d2Va
    UDAxS0dPWTc3MjVRbVJIM0VhYzBVNk9RV0tZcjhGcWZZaEx1SkIKWHpoNXd1RGlUWjMwWTUvR1pm
    blpEWFdaR2x5WldIdVdmeW4yUmVlbDdyLzFFYmR1K3lubEEra0U2VGk3empmVApSYU5FdXJPTkpu
    YmsvN3pCQjVaYkVlNkx3TTN1bVZCZTZ2Y1VPbkVDZ2dFQkFNVnJxdlJ0VjYvS0lvWDRMK3ByCjBR
    dW43S1NydjZGU0FUMk50MGI2T0c5MzBGeStWL053bmFYMTdjSFJDTDIvZGsxTWFIMlV5VU9GRk1E
    NzBsT3MKY1RLOHVpSU5HVUdnUWpEQU9VSENVZjFXY3FtUWdrTmFPQUlwbyt5Rm1iYnBoNG5kT0k3
    ZlNhOWJ3RE0xV1VncgpUQW9CeGo3c0NoeC9mVVVEbnU2c3c5VnIwdzZNVElwV2NTUGc4VFdTS1VG
    UndNa1o0ZENUTUZiNE0wbWxZdmxqCkpsL0NIUWlRWmtiMWdSSk9tcWYwR2JJZ0xXd1cvZCt5a09Q
    aktaRjc0d0ZZcFBvVWJFdWxwcjNtWkdxQ3RRTDMKcGpFN1RxWExidFZhbWJVR1NMRkErYW5LZWZC
    UzdZZTJmclJwanpsQVdqYUVaY2N5OFJSdzk1MWFQanlIV3RkMAphcTBDZ2dFQkFOS3BCNnRhMk4r
    NnFzQ1AzdnRZdk9lTlBMT1oxWkpyZGs0U0Q1QzdQSmdVYlZsdEtWK1IyQ0hmCjN4NWMzT0NES2g3
    Rm10a1pNR1BqYVg1KzkxeHIrak9OUU9KVmExUnpVVUwwZHIzOWRXSjhOTmp4NW1hd29TU1EKVVFG
    MmJEMnNZTUNLZWp0RDAxOVhUQmlIL3Z6WlkxTmtTRW9rL05sUTZTcVMvMUVncWN6U0JiS09yNFVE
    cXJkLwp3RW80aWhEbkllY3NQRmxjdGpWaUZGVDhQdG0zbzRxejM0ck50WWNkV0JBSy9YcS9zbWV2
    b2FNVWdzK0hKcjdJCjZoVnZGOW1VYjljL1dqemZhU2I0SEMzRlBBdUF1VjcwY094Zy9BVnJVM1g4
    bWErbGZoZ0pRbnlWNWlVTHVTWlAKU2xWNktCWDIwTE15T2JJUXE0UHFiQXF6Qkt3Nm5jYz0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=