---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netology-web
  name: netology-web
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: netology-web
  ports:
  - name: service-port
    protocol: TCP
    port: 8888
    targetPort: 8080