---
apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
spec:
  selector:
    app: multitool
  ports:
  - name: nginxadditional
    port: 80
    targetPort: 80
  - name: multitooladditional
    port: 8080
    targetPort: 8080